server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
jwt:
  secret_key: ${JWT_SECRET_KEY}
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${CLOUD_AWS_REGION_STATIC:ap-northeast-2}
logging:
  level:
    com.example.gameproject: INFO
